const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach. Perfect for relaxing morning walks.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1500,
    location: "Malibu",
    country: "United States",
    category: "Beaches",
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers! Walking distance to top restaurants and museums.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501183638710-841dd1904471?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "New York City",
    country: "United States",
    category: "Cities",
  },
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge alongside the deer and the bears.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1000,
    location: "Aspen",
    country: "United States",
    category: "Mountains",
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards on your doorstep.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2500,
    location: "Florence",
    country: "Italy",
    category: "Trending",
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among the canopy in this unique treehouse. Unplug, completely disconnect, and feel perfectly relaxed in the trees.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 800,
    location: "Portland",
    country: "United States",
    category: "Camping",
  },
  {
    title: "Lakeview Alpine Cabin",
    description: "Breathtaking views of the emerald lake right from your front porch. Has a wood-burning stove and a hot tub.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1503877960309-86641ab026d3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    location: "Banff",
    country: "Canada",
    category: "Lakes",
  },
  {
    title: "Iconic Paris Apartment",
    description: "View the Eiffel Tower right from your window! It has beautiful classic Parisian architecture.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 5200,
    location: "Paris",
    country: "France",
    category: "Iconic Cities",
  },
  {
    title: "Safari Tent in the Savannah",
    description: "A luxury glamping experience in the wild. See the wildlife migration directly from your doorstep.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1534011210940-bf552ae07b8a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Serengeti",
    country: "Tanzania",
    category: "Camping",
  },
  {
    title: "Scottish Castle Estate",
    description: "Live like absolute royalty in this 16th-century preserved stone castle situated on the moors.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1605649487212-4d4ce7a909a7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 11000,
    location: "Edinburgh",
    country: "Scotland",
    category: "Castles",
  },
  {
    title: "Infinity Pool Paradise",
    description: "Infinity pool dripping right off a cliff overlooking the ocean horizon.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 4900,
    location: "Bali",
    country: "Indonesia",
    category: "Amazing Pools",
  },
  {
    title: "Classic Rural Farmhouse",
    description: "Help feed the animals or just sit on the wraparound porch drinking tea in this sprawling ranch.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1599813352994-1ac3652db8ae?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 450,
    location: "Texas",
    country: "United States",
    category: "Farms",
  },
  {
    title: "Glass Igloo under Northern Lights",
    description: "A magical geodesic dome with a transparent roof perfectly suited for sleeping under the auroras.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1549486129-92b047ae3789?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2100,
    location: "Lapland",
    country: "Finland",
    category: "Arctic",
  },
  {
    title: "Forest Geodesic Dome",
    description: "Eco-friendly dome nestled into a densely wooded forest near hiking trails.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1572225648585-cdfb4d8d1e27?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 650,
    location: "Redwoods",
    country: "United States",
    category: "Domes",
  },
  {
    title: "Houseboat on the Amstel",
    description: "Float gently through the canals of Amsterdam in this luxurious converted barge.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1621508682283-fcf13c9501d5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1300,
    location: "Amsterdam",
    country: "Netherlands",
    category: "Boats",
  },
  {
    title: "Private Room in Shared Hostel",
    description: "Cheap and cheerful private room. Meet other backpackers in the shared lounge area.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 45,
    location: "Bangkok",
    country: "Thailand",
    category: "Rooms",
  },
  {
    title: "Alpine Ski Chalet",
    description: "Ski-in, ski-out directly from this snowy wood cabin in the Swiss Alps.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1418985991508-e47386d96a71?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 3300,
    location: "Zermatt",
    country: "Switzerland",
    category: "Winter",
  },
  {
    title: "Yellowstone Cabin",
    description: "Smack bang inside the national park, enjoy the natural geysers nearby.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 700,
    location: "Wyoming",
    country: "United States",
    category: "Parks",
  }
];

module.exports = { data: sampleListings };
